### ISSUE TITLE
when i run the app it show screen say that Slow internet conection

### ISSUE THREAD

**Issue by fathialfadel645** [Aquarius-blake/Social_Media#16]
you have make 2 fields in firebase when you create new user DateofBirth field and password field and its value in fire base is null and that casing an error null check operator used in a null value you but the code in try and catch so the app show screen of Slow internet connection

**Comment by Aquarius-blake** [comment]
I forgot to remove the password field since it's never used, however both fields are nullable, so it shouldn't be a problem. The slow internet connection screen is shown because the non-nullable field values have not been gotten from firebase yet.

**Comment by Aquarius-blake** [comment]
You are welcome and thanks to you as well
